version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8081
    environment: 
      spring.datasource.url: jdbc:postgresql://postgres_db:5432/library10
    depends_on:
      - postgres_db
    
  postgres_db:
    image: "postgres:11.4"
    restart: always
    ports:
      - 5432:5433
    environment:
      POSTGRES_DB: library10
      POSTGRES_PASSWORD: geetha